### ISSUE TITLE
API Endpoint to give the hash of the config json blob being used

### ISSUE THREAD

**Issue by amwelch** [eliothedeman/bangarang#29]
Used as a simple sanity check to make sure that new config takes.

**Comment by amwelch** [comment]
Currently have this working. Just need to add some tests then I will submit a PR.

curl localhost:8081/api/config/hash
{"hash":"59adb24ef3cdbe0297f05b395827453f"}

**Comment by eliothedeman** [comment]
This has been updated by my latest pull request.
